sudo: true
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable

matrix:
    allow_failures:
        - rust: nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo test
  - cargo fmt -- --check
