[package]
name = "config"
version = "0.7.0"
description = "Layered configuration system for Rust applications."
homepage = "https://github.com/mehcode/config-rs"
repository = "https://github.com/mehcode/config-rs"
readme = "README.md"
keywords = ["config", "configuration", "settings", "env", "environment"]
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
categories = ["config"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "mehcode/config-rs" }

[features]
default = ["toml", "json", "yaml", "hjson"]
json = ["serde_json"]
yaml = ["yaml-rust"]
hjson = ["serde-hjson"]

[dependencies]
lazy_static = "0.2"
serde = "^1.0.8"
# nom = "^3.0.0"
nom = { git = "ssh://git@github.com/snipsco/nom", rev = "3769283" }

toml = { version = "^0.4.1", optional = true }
serde_json = { version = "^1.0.2", optional = true }
yaml-rust = { version = "^0.3.5", optional = true }
serde-hjson = { version = "^0.8.1", optional = true }

[dev-dependencies]
serde_derive = "^1.0.8"
float-cmp = "0.2.3"
chrono = { version = "0.4", features = ["serde"] }
