[package]
name = "config"
version = "0.2.0"5
description = "Layered configuration system for Rust applications."
homepage = "https://github.com/mehcode/config-rs"
repository = "https://github.com/mehcode/config-rs"
readme = "README.md"
keywords = [
    "config",
    "configuration",
    "settings",
    "env",
    "environment"
]
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]

[features]
default = ["toml"]
json = ["serde_json"]

[dependencies]
toml = { version = "0.2.1", optional = true }
serde_json = { version = "0.9", optional = true }
